# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Lambda
import os
from PyQt5.QtCore import Qt,QPoint,QUrl
from lib2to3.pgen2.pgen import generate_grammar
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import* 
from PyQt5 import uic
import random as rd
import datetime
import time
from PyQt5.QtCore import QRect, QPropertyAnimation
from PyQt5.QtMultimedia import QMediaPlayer ,QMediaContent


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 542)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-4, -8, 1271, 551))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/tileable-horizontal-background-wild-west-set1-vector-4254940.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.labelwheels = QtWidgets.QLabel(self.centralwidget)
        self.labelwheels.setGeometry(QtCore.QRect(530, 90, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelwheels.setFont(font)
        self.labelwheels.setObjectName("labelwheels")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1030, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(203, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.generatebutton = QtWidgets.QPushButton(self.centralwidget)
        self.generatebutton.setGeometry(QtCore.QRect(90, 70, 75, 23))
        self.generatebutton.setObjectName("generatebutton")
        self.SPOILEDRAILSNUM = QtWidgets.QLabel(self.centralwidget)
        self.SPOILEDRAILSNUM.setGeometry(QtCore.QRect(1210, 90, 47, 31))
        self.SPOILEDRAILSNUM.setStyleSheet("gridline-color: rgb(255, 255, 255);")
        self.SPOILEDRAILSNUM.setText("")
        self.SPOILEDRAILSNUM.setObjectName("SPOILEDRAILSNUM")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 30, 0, 0))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.SPOILEDWHEELsNUM = QtWidgets.QLabel(self.centralwidget)
        self.SPOILEDWHEELsNUM.setGeometry(QtCore.QRect(1210, 50, 47, 31))
        self.SPOILEDWHEELsNUM.setStyleSheet("gridline-color: rgb(255, 255, 255);")
        self.SPOILEDWHEELsNUM.setText("")
        self.SPOILEDWHEELsNUM.setObjectName("SPOILEDWHEELsNUM")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 430, 791, 21))
        self.label_7.setStyleSheet("image: url(:/newPrefix/Untitled.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.labelwagonsNUM = QtWidgets.QLabel(self.centralwidget)
        self.labelwagonsNUM.setGeometry(QtCore.QRect(650, 20, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelwagonsNUM.setFont(font)
        self.labelwagonsNUM.setStyleSheet("\n"
"color: rgb(0, 255, 0);")
        self.labelwagonsNUM.setText("")
        self.labelwagonsNUM.setObjectName("labelwagonsNUM")
        self.newtrainbutton = QtWidgets.QPushButton(self.centralwidget)
        self.newtrainbutton.setGeometry(QtCore.QRect(20, 460, 75, 51))
        self.newtrainbutton.setObjectName("newtrainbutton")
        self.SPOILEDWAGONSNUM = QtWidgets.QLabel(self.centralwidget)
        self.SPOILEDWAGONSNUM.setGeometry(QtCore.QRect(1210, 0, 47, 41))
        self.SPOILEDWAGONSNUM.setStyleSheet("gridline-color: rgb(255, 255, 255);")
        self.SPOILEDWAGONSNUM.setText("")
        self.SPOILEDWAGONSNUM.setObjectName("SPOILEDWAGONSNUM")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1030, 0, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(203, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 430, 791, 21))
        self.label_5.setStyleSheet("image: url(:/newPrefix/Untitled.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gobutton = QtWidgets.QPushButton(self.centralwidget)
        self.gobutton.setGeometry(QtCore.QRect(130, 460, 75, 51))
        self.gobutton.setObjectName("gobutton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1030, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(203, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 430, 791, 21))
        self.label_8.setStyleSheet("image: url(:/newPrefix/Untitled.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.labelwheelsNUM = QtWidgets.QLabel(self.centralwidget)
        self.labelwheelsNUM.setGeometry(QtCore.QRect(650, 90, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelwheelsNUM.setFont(font)
        self.labelwheelsNUM.setStyleSheet("color: rgb(12, 255, 154);\n"
"")
        self.labelwheelsNUM.setText("")
        self.labelwheelsNUM.setObjectName("labelwheelsNUM")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.labelwagons = QtWidgets.QLabel(self.centralwidget)
        self.labelwagons.setGeometry(QtCore.QRect(530, 20, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelwagons.setFont(font)
        self.labelwagons.setObjectName("labelwagons")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(-4, 420, 1271, 20))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.TRAINMAIN = QtWidgets.QLabel(self.centralwidget)
        self.TRAINMAIN.setGeometry(QtCore.QRect(0, 370, 541, 61))
        self.TRAINMAIN.setText("")
        self.TRAINMAIN.setPixmap(QtGui.QPixmap(":/newPrefix/wdadawdadwa-removebg-preview.png"))
        self.TRAINMAIN.setScaledContents(True)
        self.TRAINMAIN.setObjectName("TRAINMAIN")
        self.speed = 15
        self.player=QMediaPlayer()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.generatebutton.clicked.connect(self.Generate)
        self.newtrainbutton.clicked.connect(self.NEWBUT)
        self.gobutton.clicked.connect(self.GOBUT)
        
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelwheels.setText(_translate("MainWindow", "Wheels:"))
        self.label_2.setText(_translate("MainWindow", "SPOILED  WHEELS :"))
        self.generatebutton.setText(_translate("MainWindow", "Generate"))
        self.newtrainbutton.setText(_translate("MainWindow", "New Train"))
        self.label_4.setText(_translate("MainWindow", "SPOILED WAGONS :"))
        self.gobutton.setText(_translate("MainWindow", "GO!"))
        self.label_6.setText(_translate("MainWindow", "SPOILED RAILS :"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Wagons"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Wheels"))
        self.labelwagons.setText(_translate("MainWindow", "Wagons:"))
   
    def Generate(self):
        val=self.comboBox.currentText()
        print(val)
        if val=="Wheels":
           self.labelwheelsNUM.setText(f"{rd.randrange(1,20)}")
        else:
           self.labelwagonsNUM.setText(f"{rd.randrange(1,20)}")
    
    def NEWBUT(self):
        self.labelwheelsNUM.setText("")
        self.labelwagonsNUM.setText("")
        self.SPOILEDWHEELsNUM.setText("")
        self.SPOILEDWAGONSNUM.setText("")
        self.SPOILEDRAILSNUM.setText("")
        self.TRAINMAIN.setGeometry(QtCore.QRect(0, 370, 541, 61))
        self.player.stop()
        self.animation.stop()


     
         


    def GOBUT(self):
        self.animation=QPropertyAnimation(self.TRAINMAIN,b'geometry')
        self.animation.setDuration(8000)
        self.animation.setStartValue(QRect(0, 370, 541, 61))
        self.animation.setEndValue(QRect(1300, 370, 541, 61))
        self.animation.start()

        self.audio()
        self.results()

    def audio(self):
        f=os.path.join(os.getcwd(),"trainsound.wav")
        url=QUrl.fromLocalFile(f)
        content=QMediaContent(url)
        self.player.setMedia(content)
        self.player.play()

    def results(self):
        self.SPOILEDWHEELsNUM.setText(f"{int(rd.randrange(1,20)/3)}")
        self.SPOILEDWAGONSNUM.setText(f"{int(rd.randrange(1,20)/3)}")
        self.SPOILEDRAILSNUM.setText(f"{int(rd.randrange(1,20)/3)}")



         
         
        
            

  
        


        


        

        
        
        
        
        
          

        

        



import resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
